### ISSUE TITLE
not reaching "DONE" response

### ISSUE THREAD

**Issue by userbox020** [Sentdex/TermGPT#3]
Querying GPT for next command (these are not running yet)...
Message History: [{'role': 'user', 'content': 'Given text input from a user looking to do programming, help to build a series of console commands that will achieve the goals of the prompt. Your responses will be one command at a time, where each response is JUST the command and nothing else. When ready for the next command, the user will say "NEXT" and you will respond with the next command. When we have reached the end of console commands, respond with "DONE" and then you will do it again with some new input from the user. If you understand, say "OK."'}, {'role': 'assistant', 'content': 'OK.'}, {'role': 'user', 'content': 'NEW STARTING INPUT: show me a basic flask web dev example with templates?'}, {'role': 'assistant', 'content': 'pip install flask'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'mkdir basic_flask_app'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "cat << 'EOF' > basic_flask_app/app.py\nfrom flask import Flask, render_template\n\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return render_template('index.html')\n\n@app.route('/about')\ndef about():\n    return render_template('about.html')\n\nif __name__ == '__main__':\n    app.run(debug=True)\nEOF"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'mkdir basic_flask_app/templates'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'cat << EOF > basic_flask_app/templates/index.html\n<!DOCTYPE html>\n<html>\n<head>\n    <title>My Flask App</title>\n</head>\n<body>\n    <h1>Welcome to My Flask App</h1>\n    <p>This is the home page!</p>\n</body>\n</html>\nEOF'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "cat << 'EOF' > basic_flask_app/templates/about.html\n<!DOCTYPE html>\n<html>\n<head>\n    <title>About My Flask App</title>\n</head>\n<body>\n    <h1>About My Flask App</h1>\n    <p>This is a simple Flask app that demonstrates the use of templates!</p>\n</body>\n</html>\nEOF\n"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'python basic_flask_app/app.py'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'DONE'}, {'role': 'user', 'content': 'NEW STARTING INPUT: --r mplexample.py'}, {'role': 'assistant', 'content': "I'm not sure what you're asking. Can you please provide more information or context?"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, I cannot provide an appropriate response based on the information given. Please provide more context or rephrase your request."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm not sure what you are requesting here. Could you please provide further details or information?"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but I still do not understand the request. Can you please provide more details or context so I can better assist you?'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context I cannot provide a response. Please provide more details or rephrase your request."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry for the confusion, but as an AI language model, I'm not able to grasp the intent behind this input. Could you please provide more context or clarify your request?"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without further information or context, I cannot provide an appropriate response. Please provide more details or rephrase your request so I can better understand how to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I apologize, but I'm not sure what I can do to help. If you could provide more details or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I'm still unsure how to assist you without more information or context. If you could provide additional details or rephrase your request, I will do my best to provide a helpful response."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I'm not sure what task or goal you are attempting to accomplish. If you could provide more information or context, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but an incomplete or unclear request was provided. Can you please provide more details or clarify your request so I can better assist you?'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without further context or information, I cannot provide an appropriate response to your input. If you could provide more details or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I cannot continue with this conversation without more information or context. If you could provide further details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I am not able to provide an appropriate response without more information or context. If you could provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but I cannot continue with this conversation without more context or information about what you are looking for. If you could provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context, I cannot provide an appropriate response to your input. If you could provide more details or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I apologize, but I'm unable to provide a helpful response based on the current input. Could you please provide more context or clarify your request?"}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I cannot continue with this conversation without more information or context. If you could provide additional details or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context, I cannot provide an appropriate response to your input. If you could please provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about what you are looking for, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I apologize, but I'm still not sure what you are requesting. If you could please provide more information or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I still need more context or information about what you are looking for. Without more details or a clearer request, I am unable to provide an appropriate response."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but I cannot continue this conversation without more information or context about your request. If you could please provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more specific details or context about your request, I am unable to provide an appropriate response. If you could please provide additional information or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I'm unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I cannot provide an appropriate response. If you could please provide additional details or clarify your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about what you are looking for, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about what you are looking for, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or clarify your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I'm not sure what you are requesting. If you could please provide more information or clarify your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but I need more information or context about your request. Without more details or a clearer request, I am unable to provide an appropriate response."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': 'I apologize, but without more information or context about your request, I am unable to provide an appropriate response. If you could please provide more details or clarify your request, I will do my best to assist you.'}, {'role': 'user', 'content': 'NEXT'}, {'role': 'assistant', 'content': "I'm sorry, but without more information or context about your request, I cannot provide an appropriate response. If you could please provide additional details or rephrase your request, I will do my best to assist you."}, {'role': 'user', 'content': 'NEXT'}]

**Comment by Sentdex** [comment]
It looks like your only input was: --r mplexample.py, so effectively just code w/o any question/desire...etc

You didn't make any request, and GPT-4 has no idea what to make of that given the prompt up to that point. 

Eventually, we might add some support for when the model truly has no idea what you want, since it's possible you just accidentally hit enter too early or something...but for now, I am not sure I'm ready to call this an issue.

Would be curious to see this looping behavior if there was a real request associated with it. I have been pretty surprised personally how rarely this happens, seems to have only occurred for me so far with error messages w/o any further context.

**Comment by userbox020** [comment]
its not an code issue, its an user issue because i dont know how to tell TermGPT to analize my code and generate the right comands to fix errors or give improve options
